name: PR Workflow

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: razorpay/docker/login-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}
      - name: build imagepullsecret-patcher image
        uses: razorpay/docker/build-push-action@v2
        with:
          tags: razorpay/imagepullsecret-patcher:${{ github.sha }}
          push: true
          file: Dockerfile
          build-args: GIT_COMMIT_HASH=${{ github.sha }}
